### ISSUE TITLE
Incomplete setup with ROS2 Foxy

### ISSUE THREAD

**Issue by AntoineHX** [bitmeal/cap-grant-ld#2]
Hi,

I'm looking for a cleaner solution than what we achieved with https://github.com/shadow-robot/ethercat_grant/issues/10 on Ubuntu 20 with ROS2 Foxy & SOEM.

Initial compilation failed with the following error :
```bash
--- stderr: cap_grant_ld
CMake Error at CMakeLists.txt:36 (file):
  file does not recognize sub-command REAL_PATH
```
REAL_PATH [require Cmake 3.19](https://cmake.org/cmake/help/latest/command/file.html#path-conversion). It might be useful to edit the CMakeList accordingly. Also, for people using ROS, [How can I update/remove cmake without partially deleting my ROS distribution?](https://answers.ros.org/question/293119/how-can-i-updateremove-cmake-without-partially-deleting-my-ros-distribution/) might be useful.

I also installed `libcap-ng-dev` & `libprocps-dev` with `rosdep install --from-paths src --ignore-src -r -y` from the workspace folder.

Compilation went fine but it seems that "<ws>/install/cap_grant_ld/share/cap_grant_ld/local_setup.bash" is missing, preventing the use of the package in a Launch file at the same time. Do you know how to solve this issue ?

Thank you for your work !
Cheers

**Comment by bitmeal** [comment]
Thank you for your input and feedback!

Not specifying the correct CMake version was an oversight on my side, thanks for pointing out!
I changed the heuristics for detecting an active ROS2/colcon build. This should resolve your issue (finally working as intended in general) and removes the need for a newer CMake version as well.

The issue was closed automatically from the commit message, if it does not solve your issue, please re-open!

**Comment by fnivek** [comment]
This doesn't work well in a Dockerfile. Neither COLCON or _ is set in in the non-interactive shell. I'm using `COLCON=1 _=colcon colcon build --packages-select cap_grant_ld` as a work around for now. The error you get without that is an ill formed if statement, since $ENV{_} returns nothing.
